### ISSUE TITLE
GPIO-CS

### ISSUE THREAD

**Issue by mortaca** [petrockblog/ControlBlockService2#13]
Any GPIO pin can be used as CS in the latest RPi versions, but I tried to make an Overlay by moving CS0 from pin 7 to 25 but ControlBlock does not recognize it.
I have recompiled bcm2835.c by changing the CS pins and also mcp23s17pi.cpp by adding the address of the new CS in pin 25 but nothing.
Could it be possible to explain what changes are necessary to be able to move CS to any GPIO?
Many thanks.

**Comment by petrockblog** [comment]
The access to the port expanders in completely implemented in https://github.com/petrockblog/ControlBlockService2/blob/master/src/controlblock/mcp23s17pi.cpp, which relies on the bcm2835 library.

**Comment by mortaca** [comment]
Yes but only allows to use BCM2835_SPI_CS0 or BCM2835_SPI_CS1 (GPIO 8 or 7) and i need to use GPIO 25 to use 8 and 7 for other purpose.
I found another library with this is simple to make.
https://www.bayceer.uni-bayreuth.de/bayeos/en/sensor_net/107622/BayEOS-Arduino/group__constants.html#ga29bba154633d37d07fa130a86e4a1f2a

**Comment by mortaca** [comment]
Please, can you showme the way to move the CS to another GPIO?

**Comment by petrockblog** [comment]
I do not know that library, sorry.
