### ISSUE TITLE
Direct /dev/input/js0 usage and ControlBlock driver

### ISSUE THREAD

**Issue by marcopiraccini** [petrockblog/ControlBlockService2#14]
Gamepad: Arcade. 
It seems that when the driver is active with games that wants to use /dev/input/js0, axis are wrong (LEFT is UP and so on). 
Not sure it's actually an "issue", but I guess has something to do with these values set: (0,2,4) here: https://github.com/petrockblog/ControlBlockService2/blob/master/src/controlblock/UInputGamepadArcade.cpp#L38

**Comment by marcopiraccini** [comment]
This fixed my issue: https://github.com/petrockblog/ControlBlockService2/pull/15

**Comment by petrockblog** [comment]
I have just merged your pull request - thanks a lot!

**Comment by petrockblog** [comment]
As it turns out, this breaks SDL compatibility, see also #29.
