### ISSUE TITLE
ControlBlockService2 doesn't install correctly

### ISSUE THREAD

**Issue by Townsperson** [petrockblog/ControlBlockService2#18]
Installing ControlBlockService2 seems to be broken currently. Following installation, the service doesn't seem to function (LED only blinks, switch can't be used to turn device off, any controls wired to ControlBlock don't function), and it doesn't generate a default config file at /etc/controlblockconfig.cfg (Creating one at that location doesn't fix anything). 

Installation of ControlBlockService (Original rather than 2, though the device is a revision 2) seems to fix LED and switch functionality, but controls are still broken.

**Comment by petrockblog** [comment]
Sorry for this bug. I have recently switched to CMake and overlooked a bug in the installation routine. This is fixed now!
