### ISSUE TITLE
Switch doesn't power on, service status doesn't show as running

### ISSUE THREAD

**Issue by DaveA-W** [petrockblog/ControlBlockService2#34]
After installing current master, my controllers are working and the power switch shuts down the Pi.   However on pressing the power button again, whilst the LED flashes slowly, it never stops flashing nor properly boots. No HDMI output or `ssh` connection becomes available. 

To get it to boot again, I have to leave the power switch toggled on, then replug the Pi at the wall.

`sudo service controlblockservice status` shows 
```
controlblockservice.service - LSB: ControlBlockService init script
   Loaded: loaded (/etc/init.d/controlblockservice; generated; vendor preset: enabled)
   Active: active (running) since Thu 2019-01-03 13:04:32 UTC; 7min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 4808 ExecStart=/etc/init.d/controlblockservice start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/controlblockservice.service
           └─4816 /usr/bin/controlblock
```
but `service --status-all` shows a minus next to `controlblockservice`.  Not running or registered properly?
`sudo service controlblockservice start` has no impact on the `service --status-all` output.

Attempting to clean & reinstall via `sudo make uninstallservice`, `uninstall`, `install`, `installservice` has had no effect.

I have also followed instructions here to try ensure HDMI output is configured correctly at boot.
https://blog.mivia.dk/solved-hdmi-working-raspberry-pi/

**Comment by petrockblog** [comment]
Closing this issue with the recent release of the updated driver.
