### ISSUE TITLE
Install process does not enable SPI

### ISSUE THREAD

**Issue by Cau5tik** [petrockblog/ControlBlockService2#35]
I recently installed Retropie 4.5.1 on a RPi 3b+ with a controlblock v2.1

As a first step, attempted to build/install ControlBlockService2. The service built successfully, but I didn't get any response from any ControlBlock inputs.

When running the ControlBlock service binary directly, I was presented with a flood of SPI communication errors.

I found [this thread on the RetroPie forum](https://retropie.org.uk/forum/topic/23383/controlblock-not-communicating-with-raspi-3b/5) that suggested I enable SPI through `raspi-config`. This solved my issues immediately.

It would be great to see enabling SPI added as a setup step in your documentation, and included with your otherwise perfect install script.

Thanks for the ControlBlock :)

**Comment by petrockblog** [comment]
This should be solved with the latest update (bdb7d026d7e996efaba083508d0946a97b2eeff5)
